title: "Columbia DAP Lab"
description: ""
baseurl: "" # Keep this blank for GitHub Pages root
url: "https://daplab.cs.columbia.edu"
theme: minima # Default theme, or replace with your theme
plugins:
  - jekyll-sitemap
ug_ms_application_url: "https://forms.gle/6FkeeJv43arrbN1n9"