name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to match your default branch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: "build-essential libssl-dev libffi-dev"  # Add required APT packages
          version: 1  # Change this number to force a cache refresh if needed


      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build  # This generates the _site directory

      - name: Debug - List built files
        run: ls -R _site  # Ensure the site is built before uploading

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1  # Correct action for GitHub Pages
        with:
          path: _site  # Ensure this is the correct output directory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy site
        uses: actions/deploy-pages@v1  # This correctly deploys the site
