name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to match your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Upload site artifact
        uses: actions/upload-artifact@v4  # ✅ Ensure this is v4
        with:
          name: github-pages
          path: _site  # Ensure this is the correct site output directory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4  # ✅ Ensuring artifact is downloaded before deploying
        with:
          name: github-pages
          path: _site  # Must match the upload path in the build job

      - name: Deploy site
        uses: actions/deploy-pages@v1
